tqtezos/stablecoin

- docs/specification.md
Many things need to be updated in the specification. This PR contains the most obvious fixes that I think we have agreed upon.
Resolves part of #3
- Tests
- Haddock
> [#3] Update specification: part1

- docs/specification.md
The contract specification still has a lot of inconsistencies with the actual requirements. This part has less obvious changes.
[Rendered](https://github.com/tqtezos/stablecoin/blob/gromak/specification2/docs/specification.md)
There will be one more part (hopefully only one). Plans for that part:
1. Figure out specifics regarding FA2 entrypoints. My current understanding is that FA2 is very general and our contract is, obviously, specific, so we can specify various things more precisely.
2. Maybe write entrypoint arguments more concisely (use `view` synonym, tuple syntax, specify how pseudocode is written).
3. Proofread everything, most likely some other fixes will be necessary.
Relates to #3 
- Tests
- …
> [#3] Update the specification (part 2)

- docs/specification.md
The last episode.
[Rendered](https://github.com/tqtezos/stablecoin/blob/gromak/specification3/docs/specification.md)
Resolves #3
- Tests
- Haddock
> [#3] Update specification (part 3)

- docs/specification.md
We've got some information about whitelisting/blacklisting in stablecoin. This PR updates the specification to reflect this information. Additionally, I have slightly updated `FA2 Specifics`.
#3 
- Tests
- Haddock
> Specify whitelisting/blacklisting

- README.md
- docs/specification.md
- haskell/README.md
- ligo/README.md
Another portion of specification updates based on recent discussions.
[Rendered specification](https://github.com/tqtezos/stablecoin/blob/gromak/update-spec-again/docs/specification.md)
Resolves #32 
Resolves #33 
- Tests
- Haddock
> Update the specification

- .buildkite/pipeline.yml
Problem: We want to be notified in case of scheduled job failure.
Solution: Add notification which will send a letter to
'tezos-alerts@serokell.io'.
Relates #37
- Tests
- Haddock
> [#37] Add notifications for scheduled jobs

- docs/specification.md
- haskell/package.yaml
- haskell/src/Indigo/Contracts/Safelist.hs
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/stack.yaml
- haskell/stack.yaml.lock
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/Stablecoin.hs
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/operator.ligo
- ligo/stablecoin/spec.ligo
1. Implements `set_safelist` entrypoint.
2. Adds call to a safelist contract whos address might be in storage in transfer, mint and burn entrypoints.
3. Also includes test using a dummy safelist contract implemented in indigo.
Resolves #35 
- Tests
- Haddock
> [#35] Implement safelist interaction

- docs/specification.md
- haskell/stack.yaml
- haskell/stack.yaml.lock
- haskell/test/Lorentz/Contracts/Test/Management.hs
- ligo/stablecoin/core.ligo
Since stablecoin contract can't spend tokens transfered to it we need to prohibit all non-zero transfers to it and so we are adding an additional validation that prohibits non-zero XTZ transfers.
Resolves #41 
- Tests
- Haddock
> [#41] Prohibit non-zero transfers to stablecoin contract

- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/FA2.hs
- ligo/stablecoin/actions.ligo
Fix contract so that it does not fail if the source of a zero amount transfer does not exist. And if the transfer is non-zero, fail with INSUFFICIENT_BALANCE error.
Resolves #56 
- Tests
- Haddock
> [#56] Permit non existent src for zero transfers

- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/FA2.hs
- ligo/stablecoin/hooks.ligo
- ligo/stablecoin/spec.ligo
In the latest FA2 version there are some changes regarding transfer hooks. We should update our code and specification. Note, that specification wasn't updated since the actual renaming appeared in #57. 
Resolves #55
- Tests
- Haddock
> [#55] Update owner hook logic to match FA2

- docs/specification.md
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/operator.ligo
Here I clean-up `Errors` section in the spec, also update some error messages. See commits for details.
Resolves #53
- Tests
- Haddock
> [#53] Update The description of errors

- .github/pull_request_template.md
- ChangeLog.md
- docs/specification.md
I've found some inconsistencies between our specification and code. Here I resolve them.
Note that it's based on #61 which should be merged first.
Resolves #39
- Tests
- Haddock
> [#39] Update specification according to the latest contract changes

- docs/specification.md
See https://github.com/tqtezos/stablecoin/pull/49#issuecomment-641220397
Resolves #44 
- Tests
- Haddock
> [#44] Forget about the transfer hook

- haskell/package.yaml
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/SMT.hs
- haskell/test/Stablecoin.hs
Adds SMT tests for stablecoin contract.
Resolves #42 #43
- Tests
- Haddock
> [#42]  SMT tests

- docs/specification.md
- haskell/src/Indigo/Contracts/Safelist.hs
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/spec.ligo
This PR amends safelist contract interface as per the recent changes to the FA2 spec. Specifically change 
```
type safelist_transfer_item is record
from_ : address
; to_ : list(address)
end
```
to
```
type safelist_tos is record
tos : list(address)
end
type safelist_transfer_item is
(address * safelist_tos)
```
Resolves #62 
- Tests
- Haddock
not essential.
> [#62] Amend safelist interface to match latest FA2

- .buildkite/pipeline.yml
- default.nix
- haskell/.weeder.yaml
- haskell/nettest/Main.hs
- haskell/package.yaml
- haskell/src/Indigo/Contracts/Safelist.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/SMT.hs
- nix/sources.json
- scripts/lint.sh
Add hlint and weeder steps to the CI pipeline.
TODO: figure out whether we want to use new weeder as well.
Resolves partially #52 
- Tests
- Haddock
not essential.
> [#52] update CI pipeline

- .buildkite/pipeline.yml
- Makefile
- default.nix
- haskell/Makefile
- nix/sources.json
This PR adds an ability to optimize generated ligo contract via `morley-optimize`.
An optimized contract is used as a test resource in CI.
Resolves #48 
- Tests
- Haddock
not essential.
> [#48] morley optimizer integration

- docs/specification.md
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/FA2.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/SMT.hs
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/operator.ligo
- ligo/stablecoin/spec.ligo
This PR updates stablecoin contract according to recent FA2 changes, specifically [!66](https://gitlab.com/tzip/tzip/-/merge_requests/66) and [!67](https://gitlab.com/tzip/tzip/-/merge_requests/67)
But note, that [!67](https://gitlab.com/tzip/tzip/-/merge_requests/67) is about updating transfer parameter which is done already here and mostly 
for their inner code conversion refactoring and document restructure, so only [!66](https://gitlab.com/tzip/tzip/-/merge_requests/66) is left to be
done.
Resolves #68 
- Tests
- Haddock
not essential.
> [#68] Address to recent FA2 changes (part 2)

- ChangeLog.md
- haskell/package.yaml
Problem: we have finished all issues, now it's time to release
version 1.0.0 of the contract.
Solution: update changelog and version of the haskell package.
None
- Tests
- Haddock
not essential.
> [Chore] Prepare 1.0.0 release

- .buildkite/pipeline.yml
- .gitignore
- ChangeLog.md
- LICENSES/LicenseRef-MIT-Klein.txt
- default.nix
- docs/specification.md
- haskell/nettest/Main.hs
- haskell/nettest/Nettest.hs
- haskell/src/Indigo/Contracts/Transferlist/External.hs
- haskell/src/Indigo/Contracts/Transferlist/Internal.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/SMT.hs
- haskell/test/resources/transferlist.tz
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/spec.ligo
Resolves #75 
- Tests
- Haddock
not essential.
> [#75] Transferlist

- .buildkite/pipeline.yml
Problem: sometimes nettest step gets stuck and runs for hours without
making any progress
Solution: add timeout to make the step fail if it runs for too long
None
- Tests
- Haddock
not essential.
> Add timeout to nettest step

- ChangeLog.md
- docs/specification.md
- haskell/nettest/StablecoinClientTest.hs
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/src/Stablecoin/Client/Cleveland/Caps.hs
- haskell/src/Stablecoin/Client/Cleveland/IO.hs
- haskell/src/Stablecoin/Client/Cleveland/StablecoinImpl.hs
- haskell/src/Stablecoin/Client/Contract.hs
- haskell/src/Stablecoin/Client/Impl.hs
- haskell/src/Stablecoin/Client/Main.hs
- haskell/src/Stablecoin/Client/Parser.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/FA2.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/SMT.hs
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/hooks.ligo
- ligo/stablecoin/spec.ligo
Main changes are:
1. Remove 'total_supply' from storage, update debit_from function, update Integrational and SMT tests, update client.
2. Remove pemission description entrypoint, change transfer operation to not call owner hooks, remove hook related code, update tests, update client and update documentation.
Resolves #85 
- Tests
- Haddock
not essential.
> [#85] Remove total supply and permission descriptor.

- .buildkite/pipeline.yml
Problem: Scheduled nettest run again fails due to insufficient timeout.
Solution: Increase it to 120 minutes.
None
- Tests
- Haddock
not essential.
> Increase scheduled job timeout

- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/src/Stablecoin/Client/Parser.hs
Problem: Currently in some places we hardcode token name and symbol as
"USDC". It's not desired
Solution: Change token name to "Test" and token symbol to "TEST".
Resolves #103
- Tests
- Haddock
not essential.
> [#103] Change default/hardcoded token metadata

- docs/specification.md
Includes a spec update that was missed with earlier #96 
Resolves #91
- Tests
- Haddock
not essential.
- [  ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
> [#91] Update specification doc

- haskell/nettest/Main.hs
- haskell/nettest/Nettest.hs
- haskell/nettest/Permit.hs
- haskell/nettest/StablecoinClientTest.hs
- haskell/package.yaml
- haskell/src/Indigo/Contracts/Transferlist/Internal.hs
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- haskell/src/Stablecoin/Client/Cleveland/Caps.hs
- haskell/src/Stablecoin/Client/Contract.hs
- haskell/src/Stablecoin/Client/Impl.hs
- haskell/src/Stablecoin/Client/Main.hs
- haskell/stack.yaml
- haskell/stack.yaml.lock
- haskell/test/Lorentz/Contracts/Test/Permit.hs
- haskell/test/SMT.hs
- haskell/test/Stablecoin.hs
Added integration tests for the new permit features that run on a real network.
Resolves #107
- Tests
- Haddock
not essential.
> [#107] Write Nettest tests for the new permit features

- .buildkite/pipeline.yml
- default.nix
- nix/sources.json
Problem: We want to test our contracts and library on new testnet.
Solution: Add scheduled nettest run on delphinet.
https://issues.serokell.io/issue/TM-455
- Tests
- Haddock
not essential.
> Nightly delphinet runs

- ChangeLog.md
- docs/specification.md
- haskell/nettest/Nettest.hs
- haskell/nettest/Permit.hs
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/src/Stablecoin/Client/Impl.hs
- haskell/test-common/Lorentz/Contracts/Test/Common.hs
- haskell/test/Lorentz/Contracts/Test/FA2.hs
- haskell/test/Lorentz/Contracts/Test/Management.hs
- haskell/test/Lorentz/Contracts/Test/Permit.hs
- haskell/test/SMT.hs
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/operator.ligo
- ligo/stablecoin/spec.ligo
Include change in https://gitlab.com/tzip/tzip/-/merge_requests/85 w.r.t `update_operators`.
Resolves #110 
- Tests
- Haddock
not essential.
> [#110] Include FA2 recent changes to update_operators parameter.

- ChangeLog.md
- haskell/package.yaml
Problem: Among other things, we've implemented TZIP-17 and updated the
contract to reflect recent changes to the FA2 spec. For this reason, we
want to make a new release.
Solution: bump Haskell package version, update changelog.
Resolves #117 
- Tests
- Haddock
not essential.
> [Chore] [#117] 1.3.0 release

- haskell/package.yaml
- haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs
- haskell/test/SMT.hs
- haskell/test/Stablecoin.hs
Problem: our state machine tests currently use `QuickCheck` as the
underlying library. However, QuickCheck support is being
[removed](https://gitlab.com/morley-framework/morley/-/merge_requests/610)
from `morley` and `cleveland` in favor of `hedgehog`.
In particular, `integrationalTestProperty` is being removed, along with
`Arbitrary` instances.
We should stop using these functions to be able to migrate to newer
versions of those libraries.
Solution: mechanically replace QuickCheck usages to their hedgehog
counterparts.
Resolves #127
- Tests
- Haddock
not essential.
> [#127] Migrate SMT module to use Hedgehog

- README.md
- haskell/README.md
- ligo/Makefile
- ligo/README.md
Update documentation:
1. Update gas and transaction costs for the latest version.
2. Make README files more attractive to newcomers.
Resolves #133
Resolves #137
- Tests
- Haddock
not essential.
> [#133] [#137] Update documentation

- .buildkite/pipeline.yml
- default.nix
Interface for invoking haddock build changed in newer haskell.nix,
derivation for haddock needs to be built explicitly now
https://issues.serokell.io/issue/OPS-1128
- Tests
- Haddock
not essential.
> CI: fix building haddock

- haskell/test/SMT.hs
Problem: An instance of SMT failure was found in a recent PR. It can be
triggerred by test arguments  '--hedgehog-replay
"Size 18 Seed 613762895755730128 14866453392481836605"'.
Solution: It was found to be caused by a bug in the SMT Haskell model in
the burn operation in a fold call which did not use input accumilator
and insted use the starting value in scope. Fixed it by extracting the
function out and fixing the fold call.
Resolves #
- Tests
- Haddock
not essential.
> Fix SMT Test failure

- haskell/README.md
- ligo/README.md
Small fixes in README requested by @pasqu4le.
None, it's some minor polishing.
- Tests
- Haddock
not essential.
> Update README files

- ChangeLog.md
- Makefile
- README.md
- docs/specification.md
- haskell/README.md
- haskell/package.yaml
- haskell/src/Lorentz/Contracts/Stablecoin.hs
- ligo/README.md
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/fa1.2/actions.ligo
- ligo/stablecoin/fa1.2/spec.ligo
- ligo/stablecoin/hooks.ligo
- ligo/stablecoin/metadata.ligo
- ligo/stablecoin/operator.ligo
- ligo/stablecoin/permit.ligo
- ligo/stablecoin/spec.ligo
Small documentation and performance suggestions.
More detailed explanation in each commit's message.
**Mesured costs before changes**
- Originated smart contract Stablecoin FA1.2 with address [KT1PSb9pPpAtLQcN8JFe18AoXn8K5CxL1UJS](https://better-call.dev/delphinet/KT1PSb9pPpAtLQcN8JFe18AoXn8K5CxL1UJS)
- Originated smart contract Stablecoin FA2 with address [KT1Ds8worP2asZ4njpUxe8LLWkrGiTNTWzgD](https://better-call.dev/delphinet/KT1Ds8worP2asZ4njpUxe8LLWkrGiTNTWzgD)
|             | FA1.2 Gas cost | FA2 Gas cost | FA1.2 Tx cost | FA2 Tx cost |
| ----------- | -------------- | ------------ | ------------- | ----------- |
| origination | 73988          | 74117        | 3.143178 ꜩ    | 3.168804 ꜩ  |
| transfer    | 76196          | 76740        | 0.007978 ꜩ    | 0.008047 ꜩ  |
**Mesured costs …
> Small documentation and performance suggestions

- ChangeLog.md
- README.md
Problem: We have implemented the following major changes,
* Removed `token_metadata_registry` entrypoint from the contract.
* Add TZIP-16 storage views as required by TZIP-12 to the metadata.
So we want to make a new release.
Solution: Update changelog to include the new release and update README
with gas/transaction costs.
- Tests
- Haddock
not essential.
> [Chore] 1.6.0 release

- .buildkite/pipeline.yml
- haskell/README.md
- haskell/nettest/FA1_2Comparison.hs
- haskell/nettest/Nettest.hs
- haskell/nettest/Permit.hs
- haskell/src/Stablecoin/Client/Cleveland/Caps.hs
- haskell/src/Stablecoin/Client/Parser.hs
- haskell/stack.yaml
- haskell/stack.yaml.lock
- nix/sources.json
- scripts/ci/run-local-chain-nettest.sh
Problem: New protocol arrived.
Solution: Run network tests on 008 local-chain and edonet.
Based on https://gitlab.com/morley-framework/morley/-/merge_requests/760
https://issues.serokell.io/issue/TM-491
- Tests
- Haddock
not essential.
> Add 008 network tests 

- ChangeLog.md
- README.md
- haskell/package.yaml
We have updated the dependencies in order to run network tests with the 008 protocol.
For this reason, we want to make a new (minor) release.
None
- Tests
- Haddock
not essential.
> [Chore] 1.7.1 release

- .buildkite/pipeline.yml
- nix/sources.json
Problem: New Tezos protocol arrived, we'd like to run tests for our projects on it.
Solution: Add 009-related jobs to CI config.
https://issues.serokell.io/issue/TM-525
- Tests
- Haddock
not essential.
> [TM-525] Florencenet in CI

- .buildkite/pipeline.yml
An incorrect url was added previously.
https://issues.serokell.io/issue/TM-554
- Tests
- Haddock
not essential.
> Fix granadanet node url

- default.nix
- haskell/src/Indigo/Contracts/Transferlist/External.hs
- nix/sources.json
Update dependencies used by CI, to keep them up to date.
https://issues.serokell.io/issue/OPS-1269
- Tests
- Haddock
not essential.
> CI: bump dependencies

- .buildkite/pipeline.yml
- nix/sources.json
Problem: Tezos has a new protocol and we should check if this project is
compatible with it.
Solution: Add local-chain and scheduled testnet jobs for the new
protocol to the CI configuration.
https://issues.serokell.io/issue/TM-595
- Tests
- Haddock
not essential.
> [Chore] Add hangzhou CI steps 

- .buildkite/pipeline.yml
- nix/sources.json
To propagate
https://gitlab.com/morley-framework/morley-infra/-/merge_requests/4.
Resolves #
- Tests
- Haddock
not essential.
> [Chore] Bump morley-infra

- ChangeLog.md
- ligo/Makefile
- ligo/README.md
- ligo/stablecoin/actions.ligo
- ligo/stablecoin/core.ligo
- ligo/stablecoin/fa1.2/actions.ligo
- ligo/stablecoin/fa1.2/core.ligo
- ligo/stablecoin/fa1.2/permit.ligo
- ligo/stablecoin/fa1.2/spec.ligo
- ligo/stablecoin/fa1.2/spender_allowances.ligo
- ligo/stablecoin/hooks.ligo
- ligo/stablecoin/metadata.ligo
- ligo/stablecoin/operator.ligo
- ligo/stablecoin/permit.ligo
- ligo/stablecoin/spec.ligo
- nix/sources.json
We're using a really old version of LIGO, 0.10.0. This PR updates the contract to be compatible with the latest version, 0.46.1
Resolves #185 
- Tests
- Haddock
not essential.
> [#185] Update to ligo 0.46.1

- ChangeLog.md
- README.md
- haskell/package.yaml
Preparing the 1.7.3 release.
Resolves #194
- Tests
- Haddock
not essential.
> [Chore] 1.7.3 release

- .buildkite/pipeline.yml
- default.nix
- nix/sources.json
Update xrefcheck to v0.2.2
[xrefcheck issue 148](https://github.com/serokell/xrefcheck/issues/148)
- Tests
- Haddock
not essential.
> [Chore] Update xrefcheck to v0.2.2

- README.md
Adds a warning for the upcoming Morley deprecation to the relevant docs.
None
- Tests
- Haddock
not essential.
> [Chore] Add warnings for the upcoming deprecation of Morley

- .buildkite/pipeline.yml
- flake.lock
- haskell/package.yaml
- haskell/src/Lorentz/Contracts/Stablecoin/Types.hs
- haskell/stack.yaml
- haskell/test/Lorentz/Contracts/Nettest/Nettest.hs
- haskell/test/SMT.hs
Problem: we want to test on Nairobinet
Solution: bump morley-infra, add Nairobinet CI jobs
Part of [TM-680](https://issues.serokell.io/issue/TM-680)
- Tests
- Haddock
not essential.
> [Chore] Add Nairobinet tests to CI

- .buildkite/pipeline.yml
- .gitignore
- flake.lock
- flake.nix
- haskell/hpack/definitions.yaml
- haskell/package.yaml
- haskell/src/Indigo/Contracts/Transferlist/Internal.hs
- haskell/src/Lorentz/Contracts/Stablecoin/Metadata.hs
- haskell/src/Lorentz/Contracts/Stablecoin/Types.hs
- haskell/src/Stablecoin/Util.hs
- haskell/stack.yaml
- haskell/stack.yaml.lock
- haskell/test/Lorentz/Contracts/Nettest/Nettest.hs
Resolves #
- Tests
- Haddock
not essential.
> [Chore] Update to LTS-21, remove weeds

- README.md
- flake.lock
- haskell/stack.yaml
- haskell/stack.yaml.lock
Just what it says on the title.
None
- Tests
- Haddock
not essential.
> [Chore] Bump morley to latest release and update deprecation's warnings

- .buildkite/pipeline.yml
Problem: we allowed xrefcheck failures due to what appears to have been a transient issue with github.com. We don't really want to allow failures though.
Solution: forbid xrefcheck step failures.
Context: I looked throug, and xrefcheck didn't fail for a while, I'm pretty sure it was a transient failure on github's side.
Resolves #205
- Tests
- Haddock
not essential.
* …
> [#205] Require xrefcheck CI step to pass
