docs/specification.md, haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, ligo/stablecoin/actions.ligo, ligo/stablecoin/spec.ligo
In the latest [FA2](https://gitlab.com/tzip/tzip/-/blob/b916f32718234b7c4016f46e00327d66702511a2/proposals/tzip-12/tzip-12.md) version there is only `operator_transfer_policy` which combines former `self_transfer_policy` and `operator_transfer_policy`. Our code was not updated to account for that and so this MR resolves this problem.
Resolves #54 
partly #55 (renames `owner_no_op` to `owner_no_hook`)
- Tests
- Haddock
=> [#54] Update operator policies according to recent FA2 changes

.buildkite/pipeline.yml
Problem: Local-chain tests are a bit flaky and may fail due to network
problems that don't really indicate any bugs. Restarting them manually
and getting extra notifications about failed builds can be annoying.
Solution: Allow nettest retry one time in case of failure.
https://issues.serokell.io/issue/TM-417
Resolves #37 
- Tests
- Haddock
not essential.
=> [TM-417] Allow nettests run fail once

haskell/nettest/Main.hs, haskell/nettest/Nettest.hs, haskell/src/Indigo/Contracts/Safelist.hs, haskell/stack.yaml, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/SMT.hs
Problem: We need to test our stablecoin contract against
real network to ensure that all the entryopints are called
properly.
Solution: Add nettest scenario that calls all entryopints.
Resolves #45 
- Tests
- Haddock
not essential.
=> [#45] Add nettest scenario that covers all entryoints

.buildkite/pipeline.yml
Problem: Scheduled nettest runs tend to fail every time, looks like 1
hour is not enough to complete nettest scenario on carthagenet.
Solution: Increase timeout to 90 minutes.
Resolves #
- Tests
- Haddock
not essential.
=> Increase nettest step timeout

.buildkite/pipeline.yml, default.nix, haskell/src/Stablecoin/Client/Impl.hs
Problem: In #77, we added the `stablecoin-client` executable. Users
don't want to build it from sources, we need to make it more convenient
to obtain it. 
Solution: Configure CI to build an artifact with the static executable.
Example build with the `stablecoin-client` artifact: https://buildkite.com/serokell/stablecoin/builds/754#4cf20eff-41e8-4866-97c0-f0b9a07f1707
Resolves #78
- Tests
- Haddock
not essential.
=> [#78] Produce static stablecoin-client for linux on CI

ChangeLog.md, haskell/package.yaml, nix/sources.json
Problem: we want to check how recent ligo changes affect
the size of generated Michelson code. Also we want to keep
up with ligo updates since ligo is actively developed.
Solution: update ligo version to the latest `dev` branch
using the following command:
> niv update ligo --attribute rev=3862c0444416a2e4aba7ad116eff675cacc324d3
HEAD of `dev` was chosen because it has
https://gitlab.com/ligolang/ligo/-/merge_requests/732 that was
just recently merged and that we are interested it.
Resolves #82
- Tests
- Haddock
not essential.
=> [#82] Update ligo revision

default.nix, haskell/stack.yaml, nix/sources.json
Makes sure that haskell.nix revision used in CI is the same as most of our other projects have, to reduce number of ghc builds
OPS-1023
- Tests
- Haddock
not essential.
=> [OPS-1023] CI: update dependencies, pin hackage and stackage indexes independently

haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/SMT.hs, ligo/stablecoin/actions.ligo
Change contract that when an account ends up with a zero balance, it is removed from the ledger. Add tests for transfer and burn to check zero balance account is removed after the operations.
Resolves #86 
- Tests
- Haddock
not essential.
=> [#86] Prune zero balance accounts

default.nix, nix/sources.json, nix/sources.nix
Fixes a typo which caused pins for hackage.nix and stackage.nix to be ignored, and bumps CI dependencies
https://issues.serokell.io/issue/OPS-1023
- Tests
- Haddock
not essential.
=> CI: fix pinning hackage and stackage, bump dependencies

.buildkite/pipeline.yml
Scheduled jobs always fail and retry due to insufficient timeout. In total it consumes ~8h of bk agent time.
One day we'll have dedicated bk agent for scheduled jobs, but for now retry is removed and timeout is increased
once again.
Resolves #
- Tests
- Haddock
not essential.
=> Remove scheduled retries

.buildkite/pipeline.yml, .gitignore, Makefile, default.nix, haskell/Makefile, haskell/nettest/FA1_2.hs, haskell/nettest/Main.hs, haskell/package.yaml, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/src/Lorentz/Contracts/StablecoinFA1_2.hs, haskell/stack.yaml, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA1_2.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/Lorentz/Contracts/Test/Permit.hs, haskell/test/SMT.hs, ligo/Makefile, ligo/stablecoin/fa1.2/actions.ligo, ligo/stablecoin/fa1.2/core.ligo, ligo/stablecoin/fa1.2/permit.ligo, ligo/stablecoin/fa1.2/spec.ligo, ligo/stablecoin/fa1.2/spender_allowances.ligo
Added a new version of stablecoin that implements FA1.2 instead of FA2.
The purpose of this contract is just to compare gas/transaction costs against the FA2 version.
I added:
* SMT tests to verify the implementation is correct
* Some simple Nettest tests, so we can originate the contract and call each FA1.2 operation once, and check the gas/transaction costs.
Here are the numbers I collected. I included links to logs and block explorers, so others can double-check my numbers.
Full nettest log: https://gist.githubusercontent.com/dcastro/e50489a46eb54fc69ce1667a3f42127a/raw/050ccf99fabc7b64a003bc1b89c1dad1e96735f2/complete.log
Block explorer: https://better-call.dev/carthagenet/KT1VuoysRj6tWFXAjrbQd67YMnTMi3SpNTdC/operations
* Origination:
- …
=> [#94] Implemented FA1.2 in stablecoin

haskell/nettest/Main.hs, haskell/nettest/Permit.hs, haskell/stack.yaml, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/SMT.hs, haskell/test/Stablecoin.hs
Currently we have some tests infra that looks for a specific configuration of permissions before running the tests. But this is no longer required as we are implementing specific FA2 behavior. So we can only implement such tests and can remove the test infra for permissions configuration check.
Resolves #97 
- Tests
- Haddock
not essential.
=> [#97] Cleanup redundant infra and tests

ChangeLog.md, haskell/nettest/FA1_2.hs, haskell/nettest/Main.hs, haskell/nettest/Nettest.hs, haskell/nettest/Permit.hs, haskell/src/Lorentz/Contracts/Spec/FA2Interface.hs, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/src/Lorentz/Contracts/StablecoinPath.hs, haskell/src/Stablecoin/Client/Contract.hs, haskell/src/Stablecoin/Client/Impl.hs, haskell/src/Stablecoin/Client/Main.hs, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA1_2.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/Lorentz/Contracts/Test/Permit.hs, haskell/test/SMT.hs, haskell/test/Stablecoin.hs
Problem: The Michelson representation (that is, the balancing of `pair`
and `or`s) of our Haskell data types must match the Michelson
representation of our Ligo data types.
In the past, we used Haskell nested tuples in order to have complete
control of the layout, but this leads to messy, hard to maintain code.
Solution: Now that morley introduced `customGeneric` to control an ADT's
layout, we can replace our nested tuples with Haskell ADTs and still
have control of its layout.
Resolves #102 
- Tests
- Haddock
not essential.
=> [#102] Use morley capabilities to define custom ADT layout

haskell/nettest/FA1_2Comparison.hs, haskell/nettest/Main.hs, haskell/nettest/Nettest.hs, haskell/nettest/Permit.hs, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/src/Stablecoin/Client/Contract.hs, haskell/src/Stablecoin/Client/Impl.hs, haskell/stack.yaml, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/SMT.hs, haskell/test/Stablecoin.hs
Problem: the tests use a dummy `tz2` address as the address of the
metadata registry contract. However, the FA2 spec requires that this
address be of a smart contract (i.e., a `KT1` address).
Solution: originate a valid metadata registry contract, and then put its
address in the stablecoin contract's storage.
Resolves #113
- Tests
- Haddock
not essential.
=> [#113] Use valid metadata registry in nettests

.buildkite/pipeline.yml
Problem: scheduled nettest job takes a long time to finish, making other
CI jobs wait for it
Solution: use a special runner for the nettest job
Needs serokell/serokell-profiles#540 to be deployed first
https://issues.serokell.io/issue/OPS-1066
- Tests
- Haddock
not essential.
=> Run nettest jobs on a separate agent to not stall CI for regular jobs

.buildkite/pipeline.yml
Problem: We should test our code on the new 007 protocol.
We already have nettest runs on delphinet,
but they're quite long and thus run only on schedule.
Solution: Now we have a second local-chain that runs 007
protocol. Run nettest scenario on it as well.
https://issues.serokell.io/issue/TM-457
- Tests
- Haddock
not essential.
=> Add nettest run on 007 protocol local-chain

.buildkite/pipeline.yml
Problem: 'LIGO-contract' step uploads an artifact used by the next
steps, so the next steps must not start until it has finished. It wasn't
a problem when we were using a single non-concurrent agent, but when we
added an agent for scheduled pipelines in #119, the job would fail because it
runs concurrently.
Solution: add 'wait' step to avoid running steps which use the contract
until the step which generates the contract has finished
https://issues.serokell.io/issue/OPS-1066
- Tests
- Haddock
not essential.
=> CI: add 'wait' step after uploading generated contract

haskell/stack.yaml
Problem: Now we use morley revision from hackage. However
another deps from morley repo are outdated.
Solution: Update them to the same revision as morley-1.7.1.
None
- Tests
- Haddock
not essential.
=> Bump cleveland and morley-client revision

.buildkite/pipeline.yml
Problem: we used to retry failed scheduled nettest runs on CI
beucase they are fragile, but we stopped doing that at some point
because they could stall CI completely.
Now our scheduled nettests are launched on a separate agent, so
it shouldn't be a problem to restart them once in case of failure.
Solution: add `retry` to two jobs running scheduled nettests.
None
- Tests
- Haddock
not essential.
=> Restore retries for scheduled runs

.buildkite/pipeline.yml
Problem: 007 protocol will soon be activated on mainnet, as a
consequence carthagenet will die.
Solution: Remove testing on 006 protocol because it's outdated.
https://issues.serokell.io/issue/TM-478
- Tests
- Haddock
not essential.
=> Disable testing on 006 protocol

ChangeLog.md, docs/specification.md, haskell/nettest/FA1_2Comparison.hs, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/src/Stablecoin/Client/Contract.hs, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/SMT.hs, ligo/stablecoin/actions.ligo, ligo/stablecoin/spec.ligo
We have to add `total_supply` field to the contract storage as
required by recent changes to TZIP-12. So we add it in this PR
and update spec, tests, and storage initialization functions.
Resolves #144
- Tests
- Haddock
not essential.
=> [#131] Add `total_supply` to the storage and update code/tests to keep it in sync.

.buildkite/pipeline.yml, .gitignore, ChangeLog.md, Makefile, default.nix, haskell/Makefile, haskell/nettest/FA1_2Comparison.hs, haskell/nettest/Nettest.hs, haskell/nettest/Permit.hs, haskell/nettest/StablecoinClientTest.hs, haskell/package.yaml, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/src/Lorentz/Contracts/StablecoinFA1_2.hs, haskell/src/Lorentz/Contracts/StablecoinPath.hs, haskell/src/Stablecoin/Client/Contract.hs, haskell/src/Stablecoin/Client/Impl.hs, haskell/src/Stablecoin/Client/Main.hs, haskell/src/Stablecoin/Client/Parser.hs, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA1_2.hs, haskell/test/Lorentz/Contracts/Test/TZIP16.hs, haskell/test/SMT.hs, haskell/test/Stablecoin.hs, ligo/Makefile, ligo/stablecoin/metadata.ligo, ligo/stablecoin/tzip16-metadata.ligo
1. Add a `contract-metadata.ligo` contract to hold the contract metadata. 
2. Add options to the deploy command to specify how contract metadata should be set.
Right now two options are added. 
1.  --contract-metadata-remote
If this is given, the contract-metadata contract will be deployed, originated with the contract metadata, and the address will be stored in the metadata bigmap of the main contract, with the URI formated as specified by TZIP-16
2.  --contract-metadata-raw 
If this is provided with a string, the provided string is used as such for the metadata URI.
Apart from this, the part of metadata that have been commented out to save origination cost has been enabled.
Resolves  #138 
- Tests
- Haddock …
=> [#138] Configure contract-metadata storage.

ligo/stablecoin/fa1.2/spec.ligo
There are a couple of types in the FA1.2 version of the contract that are unused and don't impact on the compiled result.
They don't create a problem, but this removes it just to clean up the LIGO source code.
None
- Tests
- Haddock
not essential.
=> Remove unused LIGO types from FA1.2 contract

README.md, haskell/src/Lorentz/Contracts/Stablecoin.hs, haskell/test/Lorentz/Contracts/Test/TZIP16.hs
Since we have added more options w.r.t deploying the contracts
and metadata, we should make it more clear how it is being done in
nettests. So the section is amended.
The TIZP-016 spec describe some top level fields, and we
include most of them in our Metadata, except for the 'description'
field. The 'NEGATIVE_TOTAL_SUPPLY' error is also missing from the list
of errors. So this PR adds them both.
- Tests
- Haddock
not essential.
=> [#131] Adds some more missing TZIP-16 metadata and amend readme.

default.nix
Problem: There is a workaround to make morley binary work when building
it via nix. This workaround was added to overcome the issue in hex-text
package. However, this issue was resolved.
Solution: Update morley building in default.nix and remove workaround.
Also, update the used morley version to the latest version from hackage.
Resolves #156
- Tests
- Haddock
not essential.
=> [#156] Update morley building in default.nix

ChangeLog.md, README.md, haskell/package.yaml, haskell/src/Stablecoin/Client/Parser.hs
We have updated the contract to adhere to the updated TZIP-016 specification as well as updated the package dependencies.
For this reason, we want to make a new release.
Additionally this PR removes an unused `stablecoin-client` option
Resolves None
- Tests
- Haddock
not essential.
=> [Chore] 1.7.0 release

default.nix, nix/sources.json, nix/sources.nix
Updates dependencies used by CI to keep them up to date
Related issue: https://issues.serokell.io/issue/OPS-1174
=> CI: bump dependencies

.buildkite/pipeline.yml
Problem: because the pipeline now runs in parallel, scheduled builds
are failing because of a non-available LIGO contract artifact.
Solution: added an explicit dependency to scheduled testing step.
https://issues.serokell.io/issue/TM-534
- Tests
- Haddock
not essential.
=> Update buildkite step dependencies

.buildkite/pipeline.yml
Problem: protocol 008 has become obsolete.
Solution: remove tests for 008 local chain and edo2net from the CI.
Resolves part of TM-546
- Tests
- Haddock
not essential.
=> [TM-546] Remove edo2net tests

.buildkite/pipeline.yml, ChangeLog.md, README.md, haskell/hpack/definitions.yaml, haskell/nettest/FA1_2Comparison.hs, haskell/nettest/Main.hs, haskell/nettest/Nettest.hs, haskell/nettest/Permit.hs, haskell/nettest/StablecoinClientTest.hs, haskell/src/Indigo/Contracts/Transferlist/External.hs, haskell/src/Lorentz/Contracts/Stablecoin/Metadata.hs, haskell/src/Lorentz/Contracts/Stablecoin/Types.hs, haskell/src/Stablecoin/Client/Cleveland/Caps.hs, haskell/src/Stablecoin/Client/Cleveland/IO.hs, haskell/src/Stablecoin/Client/Cleveland/StablecoinImpl.hs, haskell/src/Stablecoin/Client/Contract.hs, haskell/src/Stablecoin/Client/Impl.hs, haskell/stack.yaml, haskell/stack.yaml.lock, haskell/test-common/Lorentz/Contracts/Test/Common.hs, haskell/test/Lorentz/Contracts/Test/FA1_2.hs, haskell/test/Lorentz/Contracts/Test/FA2.hs, haskell/test/Lorentz/Contracts/Test/Management.hs, haskell/test/Lorentz/Contracts/Test/Permit.hs, haskell/test/Main.hs, haskell/test/SMT.hs, nix/sources.json, scripts/ci/run-local-chain-nettest.sh
Problem: We want to check whether this repo can be used with the latest
morley and new GHC version.
Solution: Bump dependencies and make required changes in the code.
https://issues.serokell.io/issue/TM-523
- Tests
- Haddock
not essential.
=> [TM-523] Bump morley and other deps

.buildkite/pipeline.yml, ChangeLog.md, README.md, haskell/package.yaml
Problem: The dependencies of this smart contract have been updated
several times since the last release and the network tests now run
on a new protocol, version 011.
For this reason, we want to make a new release.
Solution: bump Haskell package version, update changelog, update
transaction costs table in the README with hangzhounet info.
None
- Tests
- Haddock
- [ x I updated [changelog](../tree/master/ChangeLog.md) unless I am sure my changes are
not essential.
=> [Chore] 1.7.2 release

default.nix, ligo/README.md, nix/sources.json
Problem: the ligo README currently points at a rolling release version,
which is not very convenient to get in case a new version breaks
compatibility. Moreover, there are now issues with fetching such an old
ligo release from source.
Solution: set the last tested working ligo version to 0.10 and
update the nix sources to get ligo as a static binary.
None
- Tests
- Haddock
not essential.
=> [Chore] Set last Ligo version tested on a release

.buildkite/pipeline.yml, default.nix, haskell/stack.yaml, nix/sources.json
Problem: Tezos has a new protocol and we should check if this project is
compatible with it.
Solution: Replace hangzhou local-chain and scheduled testnet jobs with ithaca
in the CI configuration.
https://issues.serokell.io/issue/TM-628
- Tests
- Haddock
not essential.
=> [Chore] Replace hangzhou steps with ithaca in CI

default.nix, nix/sources.json
Problem: For some reason, after nix update, CI started to complain that ligo binary has an unexcepted hash.
Solution: Fix hash.
Resolves #
- Tests
- Haddock
not essential.
=> [Chore] Fix ligo binary hash
